name: my_bismuth_wallet
description: Bismuth Wallet app (iOS/Android).

publish_to: 'none'

version: 1.1.0+57

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  # Securley store data in a keystore
  flutter_secure_storage: ^6.0.0

  # Shared prefs
  shared_preferences: ^2.0.8

  # Flare for animations
  flare_flutter: ^3.0.2

  asn1lib: ^1.4.0
  
  # Websockets
  web_socket_channel: ^2.1.0

  # Platform-specific build info
  package_info_plus: ^3.0.2

  # Device-specific info
  device_info_plus: ^8.0.0

  # Localization
  intl: ^0.17.0

  # BigDecimal alternative
  decimal: ^1.5.0

  # Logger
  logger: ^1.1.0
  
  # A Flutter plugin that provides a WebView widget
  webview_flutter: ^3.0.4

  # With the Flutter safe_device package, you can easily implement security steps such as Jailbroken, root, emulator and fake location detection.
  #safe_device: ^1.0.9

  bip32: 
    git: 
      url: https://github.com/redDwarf03/bip32-dart.git
      ref: master

  bip39: ^1.0.6
  
  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # TouchID/FaceID
  local_auth: ^2.1.2
 
  # Eventbus
  event_taxi: ^1.0.0

  # SVG
  flutter_svg: ^1.1.6
  
  ffi: ^2.0.1

  flutter_launcher_icons: ^0.9.2

  # QR Codes
  qr_flutter: ^4.0.0

  # A flutter plugin for scanning 2D barcodes and QRCodes via camera
  barcode_scan2: ^4.1.4
  
  flutter_radar_chart: ^0.2.0

  flip_card: ^0.6.0

  scrolling_page_indicator:
    git: 
     url: https://github.com/redDwarf03/FlutterScrollingPageIndicator.git
     ref: master
  
  # Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS)
  uni_links: ^0.5.1

  # HTTP client
  http: ^0.13.4

  # Easy hexadecimal encoding and decoding
  hex: ^0.2.0

  pointycastle: ^3.4.0
  
  # A Flutter plugin to vibrate the device
  flutter_vibrate: ^1.3.0

  # Toast
  oktoast: ^3.1.5

  # Slidable list actions
  flutter_slidable: ^0.6.0-nullsafety.0

  # ****
  circular_profile_avatar: ^2.0.5

  # Lock helper
  synchronized: ^3.0.0

  # Service provider
  get_it: ^7.2.0
  
  quiver: ^3.0.1+1

  convert: ^3.0.1

  bs58check: 
    git: 
      url: https://github.com/redDwarf03/bs58check-dart.git
      ref: master

  # Validation utilities
  validators: ^3.0.0

  # Auto resize text widget
  auto_size_text: ^3.0.0

  # Avoid keyboard from overlapping text fields
  keyboard_avoider: 
    git:
      url: https://github.com/redDwarf03/keyboard_avoider.git
      ref: master

  hash:  
    git: 
      url: https://github.com/redDwarf03/hash.git
      ref: master

  fast_base58: ^0.2.1
 
  diacritic: ^0.1.3
  
  fluttericon: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  # A build system for Dart code generation and modular compilation
  hive_generator: ^1.1.1
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl_generator: ^0.3.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.0.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_my_bismuth_wallet.png"

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 400
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - assets/QR.svg
    - assets/icon.png
    - assets/sharecard_logo.svg
    - assets/pulltosend_animation.flr

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  